name: Run tests and publish report
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17

      - name: Clean up existing installations
        run: |
          sudo apt-get remove --purge -y google-chrome-stable chromium-browser chromedriver || true
          sudo apt-get autoremove -y || true
          sudo rm -rf /usr/bin/google-chrome /usr/bin/chromedriver || true


      - name: Install necessary dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip libnss3 libgconf-2-4 libxss1 libappindicator3-1 libxtst6 libgdk-pixbuf2.0-0 libasound2


      - name: Install Google Chrome
        run: |
                wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
                sudo dpkg -i google-chrome-stable_current_amd64.deb || true
                sudo apt-get install -f -y 

      - name: Install ChromeDriver
        run: |
                wget -O chromedriver-linux64.zip https://storage.googleapis.com/chrome-for-testing-public/128.0.6613.84/linux64/chromedriver-linux64.zip
                unzip chromedriver-linux64.zip -d ~/chromedriver
                ls -la ~/chromedriver/chromedriver-linux64
                sudo mv ~/chromedriver/chromedriver-linux64/chromedriver /usr/bin/chromedriver
                sudo chmod +x /usr/bin/chromedriver

      - name: Verify installations
        run: |
              google-chrome --version || echo "Google Chrome is not installed"
              chromium-browser --version || echo "Chromium is not installed"
              chromedriver --version || echo "ChromeDriver is not installed"
         
              ls -la /usr/bin/google-chrome
              ls -la /usr/bin/chromedriver

      - name: Run Chrome with debug flags
        run: |
          mkdir -p /tmp/chrome-logs
          export CHROME_LOG_FILE=/tmp/chrome-logs/chrome.log
          /usr/bin/google-chrome --headless --no-sandbox --disable-dev-shm-usage --remote-debugging-port=9222 > $CHROME_LOG_FILE 2>&1 &
          sleep 10
          cat $CHROME_LOG_FILE

      - name: Capture ChromeDriver logs
        run: |
          mkdir -p /tmp/chromedriver-logs
          export CHROMEDRIVER_LOG_FILE=/tmp/chromedriver-logs/chromedriver.log
          mvn clean test -Dchrome.headless=true
          cat $CHROMEDRIVER_LOG_FILE


      - name: Install dependencies
        run: mvn install -DskipTests

      - name: Run tests
        run: mvn clean test -Dchrome.headless=true

      - name: Load test report history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Build test report
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          gh_pages: gh-pages
          allure_history: allure-history
          allure_results: target/allure-results

      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v4
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history